owner: byts-india # GitHub username
repo: ping # GitHub repository name

sites:
  - name: Byts Admin
    url: https://dadmin.byts.co.in
  - name: Byts Website
    url: https://demo.byts.co.in
  - name: Byts Auth
    url: https://auth.byts.co.in
  - name: Byts Api
    url: https://api.byts.co.in
    
status-website:
  cname: ping.byts.co.in
  logoUrl: https://cdn.byts.co.in/images/logo.png
  name: Byts Pinger
  introTitle: "**Byts Pinger** Monitor Site Status."
  introMessage: "**Byts Pinger** Monitor Site Status."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
